name: dtp_projet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.1.0
  file_picker: ^10.1.9
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Correction de la déclaration des assets
  assets:
    - assets/fonts/

  # Déclaration correcte des polices personnalisées
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
        # Si vous avez d'autres variantes (bold, italic, etc.)
        # - asset: assets/fonts/Cairo-Bold.ttf
        #   weight: 700
        # - asset: assets/fonts/Cairo-Light.ttf
        #   weight: 300